import { contextBridge, ipcRenderer } from 'electron'
import { IPC_CHANNELS } from '@shared/types/ipc-contract'
import type { IpcResult } from '@shared/types'

/**
 * The preload bridge — the ONLY surface the renderer can reach.
 *
 * SECURITY (spec §5, §39)
 * ----------------------
 * - `contextIsolation: true` and `nodeIntegration: false` mean renderer code
 *   cannot `require('fs')`, `require('child_process')` or reach the database.
 * - This file never exposes `ipcRenderer` itself. Exposing the raw object would
 *   let any renderer script invoke arbitrary channels, which would defeat the
 *   whole allow-list. Instead every method below names one channel explicitly.
 * - Arguments are structured-cloned across the boundary, so functions, class
 *   instances and prototypes cannot cross. That is a feature: it guarantees the
 *   main process receives plain, inspectable data.
 * - Results arrive as an `IpcResult` envelope. Failures are re-thrown here as a
 *   real `Error` with the original `code` and `fields` attached, so callers can
 *   `try/catch` naturally while the UI can still branch on the error code and
 *   highlight specific form fields.
 */

/** An error reconstructed on the renderer side from a main-process failure. */
export interface BridgeError extends Error {
  code: string
  fields?: Record<string, string>
}

function makeError(error: { code: string; message: string; fields?: Record<string, string> }): BridgeError {
  const constructed = new Error(error.message) as BridgeError
  constructed.code = error.code
  if (error.fields) constructed.fields = error.fields
  return constructed
}

/**
 * Invoke a channel and unwrap the envelope.
 *
 * The `IpcResult` is resolved by main, never rejected, so this is the single
 * place that decides how a failure surfaces in the renderer.
 */
async function invoke<T>(channel: string, ...args: unknown[]): Promise<T> {
  const result = (await ipcRenderer.invoke(channel, ...args)) as IpcResult<T> | undefined

  // A missing envelope means the handler was never registered —a wiring bug
  // rather than a data problem, so say that rather than returning undefined and
  // letting the UI render a blank field.
  if (!result || typeof result !== 'object' || !('ok' in result)) {
    throw makeError({
      code: 'INTERNAL',
      message: `No response from the application for "${channel}". This is a bug; please report it.`
    })
  }

  if (result.ok) return result.data
  throw makeError(result.error)
}

/**
 * Build one method per contract entry.
 *
 * Written out explicitly rather than generated by a loop so that the exposed API
 * is auditable by reading this file: what you see here is the complete list of
 * things renderer code can ask for.
 */
const api = {
  // --- app ---------------------------------------------------------------
  appInfo: () => invoke(IPC_CHANNELS.appInfo),
  appOpenExternal: (url: string) => invoke(IPC_CHANNELS.appOpenExternal, url),

  // --- settings ----------------------------------------------------------
  settingsGet: () => invoke(IPC_CHANNELS.settingsGet),
  settingsUpdate: (patch: unknown) => invoke(IPC_CHANNELS.settingsUpdate, patch),

  // --- accounts ----------------------------------------------------------
  accountsList: (options?: unknown) => invoke(IPC_CHANNELS.accountsList, options),
  accountsGet: (id: number) => invoke(IPC_CHANNELS.accountsGet, id),
  accountsCreate: (input: unknown) => invoke(IPC_CHANNELS.accountsCreate, input),
  accountsUpdate: (id: number, input: unknown) => invoke(IPC_CHANNELS.accountsUpdate, id, input),
  accountsDelete: (id: number) => invoke(IPC_CHANNELS.accountsDelete, id),
  accountsArchive: (id: number, archived: boolean) => invoke(IPC_CHANNELS.accountsArchive, id, archived),
  accountsBalances: () => invoke(IPC_CHANNELS.accountsBalances),

  // --- categories --------------------------------------------------------
  categoriesList: (options?: unknown) => invoke(IPC_CHANNELS.categoriesList, options),
  categoriesCreate: (input: unknown) => invoke(IPC_CHANNELS.categoriesCreate, input),
  categoriesUpdate: (id: number, input: unknown) => invoke(IPC_CHANNELS.categoriesUpdate, id, input),
  categoriesDelete: (id: number, options?: unknown) => invoke(IPC_CHANNELS.categoriesDelete, id, options),
  categoriesUsage: () => invoke(IPC_CHANNELS.categoriesUsage),

  // --- transactions ------------------------------------------------------
  transactionsList: (query?: unknown) => invoke(IPC_CHANNELS.transactionsList, query),
  transactionsGet: (id: number) => invoke(IPC_CHANNELS.transactionsGet, id),
  transactionsCreate: (input: unknown) => invoke(IPC_CHANNELS.transactionsCreate, input),
  transactionsUpdate: (id: number, input: unknown) => invoke(IPC_CHANNELS.transactionsUpdate, id, input),
  transactionsDelete: (id: number) => invoke(IPC_CHANNELS.transactionsDelete, id),
  transactionsTransfer: (input: unknown) => invoke(IPC_CHANNELS.transactionsTransfer, input),
  transactionsTransferUpdate: (id: number, input: unknown) =>
    invoke(IPC_CHANNELS.transactionsTransferUpdate, id, input),
  transactionsSearch: (query: unknown) => invoke(IPC_CHANNELS.transactionsSearch, query),

  // --- dashboard & statistics -------------------------------------------
  /**
   * `range` selects a custom window and `cycleStartDay` overrides the saved
   * anchor for this request only. Both are optional, so callers that just want
   * the user's default period keep the one-argument call.
   */
  dashboardSummary: (cycleKey: string, range?: unknown, cycleStartDay?: number) =>
    invoke(IPC_CHANNELS.dashboardSummary, cycleKey, range ?? null, cycleStartDay),
  statsBiggestExpenses: (cycleKey: string, limit?: number, range?: unknown) =>
    invoke(IPC_CHANNELS.statsBiggestExpenses, cycleKey, limit, range ?? null),
  statsStatistics: (granularity: string, anchor: string) =>
    invoke(IPC_CHANNELS.statsStatistics, granularity, anchor),
  statsRange: (from: string, to: string) => invoke(IPC_CHANNELS.statsRange, from, to),
  statsKline: (granularity?: string, maWindows?: number[]) =>
    invoke(IPC_CHANNELS.statsKline, granularity, maWindows),
  statsCalendar: (monthKey: string) => invoke(IPC_CHANNELS.statsCalendar, monthKey),
  statsDayTotals: (date: string) => invoke(IPC_CHANNELS.statsDayTotals, date),
  statsMonths: () => invoke(IPC_CHANNELS.statsMonths),
  statsDailySeries: (monthKey: string) => invoke(IPC_CHANNELS.statsDailySeries, monthKey),

  // --- exchange rates ----------------------------------------------------
  ratesInfo: (quoteTargets?: string[]) => invoke(IPC_CHANNELS.ratesInfo, quoteTargets),
  ratesRefresh: (force?: boolean) => invoke(IPC_CHANNELS.ratesRefresh, force),
  ratesSetManual: (rates: Record<string, number>, base?: string) =>
    invoke(IPC_CHANNELS.ratesSetManual, rates, base),
  ratesClear: () => invoke(IPC_CHANNELS.ratesClear),

  // --- settlement cycle & custom periods ---------------------------------
  cycleInfo: (cycleKey: string) => invoke(IPC_CHANNELS.cycleInfo, cycleKey),
  cycleShift: (cycleKey: string, delta: number) => invoke(IPC_CHANNELS.cycleShift, cycleKey, delta),
  customPeriodsList: () => invoke(IPC_CHANNELS.customPeriodsList),
  customPeriodsSave: (input: unknown) => invoke(IPC_CHANNELS.customPeriodsSave, input),
  customPeriodsDelete: (id: number) => invoke(IPC_CHANNELS.customPeriodsDelete, id),
  customPeriodStats: (input: unknown) => invoke(IPC_CHANNELS.customPeriodStats, input),

  // --- receipt OCR (v1.5.2) ----------------------------------------------
  ocrStatus: () => invoke(IPC_CHANNELS.ocrStatus),
  ocrPickImage: () => invoke(IPC_CHANNELS.ocrPickImage),
  ocrRecognize: (filePath: string) => invoke(IPC_CHANNELS.ocrRecognize, filePath),

  // --- import / export ---------------------------------------------------
  importPickFile: () => invoke(IPC_CHANNELS.importPickFile),
  importParse: (filePath: string, presetId: string) => invoke(IPC_CHANNELS.importParse, filePath, presetId),
  importCommit: (request: unknown) => invoke(IPC_CHANNELS.importCommit, request),
  importBatches: () => invoke(IPC_CHANNELS.importBatches),
  importRollback: (batchId: number) => invoke(IPC_CHANNELS.importRollback, batchId),
  exportCsv: (query: unknown) => invoke(IPC_CHANNELS.exportCsv, query),
  exportXlsx: (query: unknown) => invoke(IPC_CHANNELS.exportXlsx, query),

  // --- backup ------------------------------------------------------------
  backupCreate: () => invoke(IPC_CHANNELS.backupCreate),
  backupRestore: () => invoke(IPC_CHANNELS.backupRestore),
  databaseInfo: () => invoke(IPC_CHANNELS.databaseInfo),
  databaseReveal: () => invoke(IPC_CHANNELS.databaseReveal),

  // --- budgets -----------------------------------------------------------
  budgetsList: () => invoke(IPC_CHANNELS.budgetsList),
  budgetsSet: (input: unknown) => invoke(IPC_CHANNELS.budgetsSet, input),
  budgetsDelete: (id: number) => invoke(IPC_CHANNELS.budgetsDelete, id),
  budgetsProgress: (monthKey: string) => invoke(IPC_CHANNELS.budgetsProgress, monthKey),

  // --- subscriptions -----------------------------------------------------
  subscriptionsList: () => invoke(IPC_CHANNELS.subscriptionsList),
  subscriptionsCreate: (input: unknown) => invoke(IPC_CHANNELS.subscriptionsCreate, input),
  subscriptionsUpdate: (id: number, input: unknown) => invoke(IPC_CHANNELS.subscriptionsUpdate, id, input),
  subscriptionsDelete: (id: number) => invoke(IPC_CHANNELS.subscriptionsDelete, id),
  subscriptionsMonthlyEstimate: () => invoke(IPC_CHANNELS.subscriptionsMonthlyEstimate),

  // --- recurring ---------------------------------------------------------
  recurringList: () => invoke(IPC_CHANNELS.recurringList),
  recurringCreate: (input: unknown) => invoke(IPC_CHANNELS.recurringCreate, input),
  recurringUpdate: (id: number, input: unknown) => invoke(IPC_CHANNELS.recurringUpdate, id, input),
  recurringDelete: (id: number) => invoke(IPC_CHANNELS.recurringDelete, id),
  recurringDue: (asOf?: string) => invoke(IPC_CHANNELS.recurringDue, asOf),
  recurringConfirm: (ruleId: number, date: string) => invoke(IPC_CHANNELS.recurringConfirm, ruleId, date),

  // --- demo data ---------------------------------------------------------
  demoSeed: (monthKey?: string) => invoke(IPC_CHANNELS.demoSeed, monthKey),
  demoClear: () => invoke(IPC_CHANNELS.demoClear),

  /**
   * Subscribe to data-change notifications.
   *
   * The listener is wrapped so the renderer's callback never receives the raw
   * Electron event object, which carries a `sender` capable of reaching back
   * into the IPC layer.
   *
   * Returns an unsubscribe function; React effects must call it on cleanup or
   * listeners accumulate on every mount.
   */
  onDataChanged: (callback: (payload: { reason: string }) => void): (() => void) => {
    const listener = (_event: unknown, payload: { reason: string }): void => {
      callback({ reason: payload?.reason ?? 'unknown' })
    }
    ipcRenderer.on(IPC_CHANNELS.eventDataChanged, listener)
    return () => {
      ipcRenderer.removeListener(IPC_CHANNELS.eventDataChanged, listener)
    }
  }
}

export type CashInflowBridge = typeof api

// `contextBridge` is the only sanctioned way to cross the isolation boundary.
contextBridge.exposeInMainWorld('api', api)
